import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class TasksRepository {
  constructor(private readonly prisma: PrismaService) {}

  createWorkflowTask(input: { userId: string; orderId?: string }) {
    return this.prisma.task.create({
      data: {
        title: 'Task generated by workflow',
        status: 'todo',
        userId: input.userId,
        ...(input.orderId ? { orderId: input.orderId } : {}),
      },
    });
  }
}
