import { Injectable } from '@nestjs/common';
import { ActionType } from '@prisma/client';
import { PrismaService } from '../../../prisma/prisma.service';
import { ActionHandler } from '../action-handler.interface';
import { ActionExecutionContext } from '../action-context.type';

@Injectable()
export class CreateTaskHandler implements ActionHandler {
  readonly type = ActionType.CREATE_TASK;

  constructor(private readonly prisma: PrismaService) {}

  async execute(context: ActionExecutionContext): Promise<string> {
    // Crée une tâche liée à l'utilisateur (et à la commande si disponible).
    await this.prisma.task.create({
      data: {
        title: 'Task generated by workflow',
        status: 'todo',
        userId: context.payload.userId,
        ...(context.payload.orderId ? { orderId: context.payload.orderId } : {}),
      },
    });

    return 'task created';
  }
}
